version: 2

############################################################################

jobs:
   build:
      docker:
         - image: circleci/python:2.7
      working_directory: ~/zm-timezones
      steps:
        - checkout
        - run:
            name: Primary Zone
            working_directory: ~/zm-timezones/conf/tz/tools
            command: ./checkPrimaryZones.py
        - run:
            name: Message Check
            working_directory: ~/zm-timezones/conf/tz/tools
            command: ./TzMsgCheck.pl -t ../../timezones.ics

############################################################################